CREATE DATABASE telephone;
CREATE ROLE telephone LOGIN PASSWORD '123456';
ALTER DATABASE telephone OWNER TO telephone;

database : telephone
user : telephone
mot de passe : 123456


CREATE TABLE ADMIN (
	IDADMIN SERIAL PRIMARY KEY,
	NAME VARCHAR(30),
	PASSWORD VARCHAR(50)
);
CREATE TABLE TELMA_OFFRE(
	NAME_TELMA_OFFRE VARCHAR(20),
	PRIX_TELMA_OFFRE INT,
	APPEL NUMERIC(10,2), /*1Ar/s*/
	INTERNET NUMERIC(10,2),/*200Mo*/
	SMS INT/*50*/
);

CREATE TABLE CLIENT(
	NUMERO VARCHAR(10) PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL, 
	MDP TEXT
);
CREATE TABLE OPERATEUR(
	IDOPERATEUR INT PRIMARY KEY,
	NAME VARCHAR(10)
);

CREATE TABLE ARGENT(
	NUMERO VARCHAR(10),
	IDOPERATEUR INT,
	SOLDE NUMERIC(10,2),
	DATE_DEPOT TIMESTAMP NOT NULL,
	CONSTRAINT FK_NUMERO FOREIGN KEY (NUMERO) REFERENCES CLIENT(NUMERO),
	CONSTRAINT FK_OPEERA FOREIGN KEY (IDOPERATEUR) REFERENCES OPERATEUR(IDOPERATEUR)
);
CREATE TABLE CREDIT(
	NUMERO VARCHAR(10),	
	IDOPERATEUR INT,
	SOLDE NUMERIC(10,2),
	DATE_ACHAT TIMESTAMP NOT NULL,
	CONSTRAINT FK_NUMERO FOREIGN KEY (NUMERO) REFERENCES CLIENT(NUMERO),
	CONSTRAINT FK_OPERA FOREIGN KEY (IDOPERATEUR) REFERENCES OPERATEUR(IDOPERATEUR)
);

CREATE TABLE OFFRE(
	NUMERO VARCHAR(10),
	IDOPERATEUR INT,
	NAME_OFFRE VARCHAR(10),
	PRIX_OFFRE INT,
	DATE_ACHAT TIMESTAMP NOT NULL,
	CONSTRAINT FKEY_NUMERO FOREIGN KEY (NUMERO) REFERENCES CLIENT(NUMERO),
	CONSTRAINT FK_OPERAAA FOREIGN KEY (IDOPERATEUR) REFERENCES OPERATEUR(IDOPERATEUR)
);
CREATE TABLE APPEL(	
	NUMERO VARCHAR(10),
	IDOPERATEUR INT,
	DUREE NUMERIC(10,2),
	DATE_APPEL TIMESTAMP NOT NULL,
	CONSTRAINT FK_IDOPERATEUR FOREIGN KEY (IDOPERATEUR) REFERENCES OPERATEUR(IDOPERATEUR),
	CONSTRAINT FOK_NUMERO FOREIGN KEY (NUMERO) REFERENCES CLIENT(NUMERO)
);

CREATE TABLE COUT(
	IDOPERATEUR INT,
	COUT_APPEL NUMERIC(10,2), /*EN ARIARY PAR SECONDE*/
	COUT_DEPOT NUMERIC(10,2),
	COUT_TRANSFERT NUMERIC(10,2),
	CONSTRAINT FOR_IDOPERATEUR FOREIGN KEY (IDOPERATEUR) REFERENCES OPERATEUR(IDOPERATEUR)
);

CREATE TABLE TRANSACTIONNS (
	IDTRANSACTIONNS  SERIAL PRIMARY KEY,
	NUMERO VARCHAR(10),
	SOLDE NUMERIC(10,2),
	ACTION VARCHAR(20),  /*DEPOT_ACHAT CREDIT_ ACHAT OFFRE_*/
	VALIDATION VARCHAR(5) /*  'TRUE'  OR  'FALSE' */
);
DROP TABLE TRANSACTIONNS;
DROP FUNCTION TRANSACTION_DEPOT;

CREATE TABLE COMPTE_CLIENT (
	NUMERO VARCHAR(10),
	SOLDE_MONEY NUMERIC(10,2),
	SOLDE_CREDIT NUMERIC(10,2),
	NAME_OFFRE VARCHAR(10),
	DUREE_APPEL_RESTANT NUMERIC(10,2),
	CONSTRAINT NUMCLIENT FOREIGN KEY (NUMERO) REFERENCES CLIENT(NUMERO)
);



CREATE TABLE BACK_OFFICE(
	NAME VARCHAR(30),
	NUMERO VARCHAR(10),
	SOLDEA NUMERIC(10,2),
 	NAMEOFFRE VARCHAR(10),
 	SOLDEC NUMERIC(10,2),
 	DUREE NUMERIC(10,2)
);

CREATE TABLE HISTORIQUE_APPEL(
	NUMERO_APPELANT VARCHAR(10),
	NUMERO_APPELER VARCHAR(10),
	TYPE_APPEL VARCHAR(10),
	DUREE_APPEL NUMERIC(10,2),
	DATE_APPEL TIMESTAMP NOT NULL
);

CREATE TABLE COUT(
	IDOPERATEUR SERIAL

)
/*AJOUT CREDIT :*/



/*AJOUT ARGENT :*/



/*AJOUT APPEL : */




/*CALCUL COUT D'APPEL : */



/*CALCUL COUP DE TRANSFERT : */



/*CALCUL COUP DE DEPOT :*/



/*ACHAT DE CREDIT PAR LE COMPTE : */